import 'package:flutter/material.dart';
import 'package:velocitybloom/Screen/product_modal.dart';
import 'package:velocitybloom/utils/image_const.dart';

class CategoryModalConst {
  static final listOfCategories = [
    CategoriesMenuModal(id: '1', categoryName: 'For You', image: Images.forYou),
    CategoriesMenuModal(
        id: '2', categoryName: 'Grocery', image: Images.grocery),
    CategoriesMenuModal(
        id: '3', categoryName: 'Fashion', image: Images.fashion),
    CategoriesMenuModal(
        id: '4', categoryName: 'Appliances', image: Images.appliances),
    CategoriesMenuModal(
        id: '5', categoryName: 'Mobiles', image: Images.mobiles),
    CategoriesMenuModal(
        id: '6', categoryName: 'Electronics', image: Images.electronics),
    CategoriesMenuModal(id: '7', categoryName: 'Home', image: Images.home),
    CategoriesMenuModal(
        id: '8', categoryName: 'Furniture', image: Images.furniture),
    CategoriesMenuModal(
        id: '9', categoryName: 'Toys & Baby', image: Images.toysBaby),
    CategoriesMenuModal(
        id: '9', categoryName: 'Personal', image: Images.personalCare),
    CategoriesMenuModal(
        id: '9', categoryName: 'Food & More', image: Images.foodAndMore),
    CategoriesMenuModal(id: '9', categoryName: 'Sports', image: Images.sports),
    CategoriesMenuModal(
        id: '9', categoryName: 'Medical', image: Images.medical),
  ];
}

class ProductModalConst {
  static final listOfProducts = [
    ProductMenuModal(
        id: '1',
        name: 'white Shoes without lesses',
        category: 'Shoes',
        price: 50.0,
        color: Colors.blue,
        description: 'shoes1 description having all the detail'),
    ProductMenuModal(
        id: '2',
        name: 'Shoes 2',
        category: 'Shoes',
        price: 60.0,
        color: Colors.green,
        description: 'shoes2 description having all the detail'),
    ProductMenuModal(
        id: '3',
        name: 'T-Shirt 1',
        category: 'T-Shirts',
        price: 200000.0,
        color: Colors.red,
        description: 'T-shirt description having all the detail releated to '
            'the product'),
    ProductMenuModal(
        id: '4',
        name: 'Shirt 1',
        category: 'Shirts',
        price: 30.0,
        color: Colors.yellow,
        description: 'shirt1 description having all the detail'),
    ProductMenuModal(
        id: '5',
        name: 'Makeup 1',
        category: 'Makeup',
        price: 10.0,
        color: Colors.purple,
        description: 'makeup1 description having all the detail'),
    ProductMenuModal(
        id: '6',
        name: 'white Shoes without lesses',
        category: 'Shoes',
        price: 50.0,
        color: Colors.blue,
        description: 'shoes1 description having all the detail'),
    ProductMenuModal(
        id: '7',
        name: 'white Shoes without lesses',
        category: 'Shoes',
        price: 50.0,
        color: Colors.blue,
        description: 'shoes1 description having all the detail'),
    ProductMenuModal(
        id: '8',
        name: 'white Shoes without lesses',
        category: 'Shoes',
        price: 50.0,
        color: Colors.blue,
        description: 'shoes1 description having all the detail'),
    ProductMenuModal(
        id: '9',
        name: 'white Shoes without lesses',
        category: 'Shoes',
        price: 50.0,
        color: Colors.blue,
        description: 'shoes1 description having all the detail'),
    ProductMenuModal(
        id: '10',
        name: 'white Shoes without lesses',
        category: 'Shoes',
        price: 50.0,
        color: Colors.blue,
        description: 'shoes1 description having all the detail'),
    ProductMenuModal(
        id: '11',
        name: 'white Shoes without lesses',
        category: 'Shoes',
        price: 50.0,
        color: Colors.blue,
        description: 'shoes1 description having all the detail'),
  ];
}

class ListingScreenProductMenuModalConst {
  static final listOfProductInListingScreen = [
    ListingScreenProductMenuModal(
      id: '',
      image: Images.phoneCase,
      title: 'Sprig TPU Matte Back Cover for SAMSUNG Galaxy S23 Plus 5G',
      subTitle: 'Premium quality Shock Proof TPU Back cover ',
      description:
          'Sprig brings you Premium quality Shock Proof TPU Back cover to protect your Samsung Galaxy S23 Plus Smart Phone. With a stylish look, the phone case is designed to perfectly fit and keep your Samsung Galaxy S23 Plus mobile Scratch proof and Dust proof. Perfect for outdoor activities and strong enough to protect it from bumps and accidental falls. This Samsung Galaxy S23 Plus mobile cover is 100% compatible with Standard chargers and headphones. This Samsung Galaxy S23 Plus case has a thickened design to provide complete access to all buttons and enhanced protection. Raised Screen Edges are provided to protect the Front Screen of your Samsung Galaxy S23 Plus. Accurately designed to leave out the sensors, ports, and microphone.',
      highlights: 'Purple, Grip Case, Pack of: 1',
      category: 'Mobile',
      subCategory: 'Mobile Case',
      seller: 'Sprig.Store',
      starRating: '4',
      rating: '10 rating',
      reviews: '50 reviews',
      sellingPrice: '500',
      price: '1800',
      deliveryType: 'Free delivery',
      discount: '57',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.flipCover,
      title: 'SBMS Flip Cover for Lava Yuva 2 Pro ',
      subTitle: '',
      description:
          'SBMS Flip Cover is an adorable amazing phone covers that completely enhances the looks of your phone. The main advantage is that it minimizes the scratches that can be caused to the Flip covers of the phone. It perfectly sticks to the back of your phone and make it look absolutely gorgeous. Further it is made of high quality and is highly durable in nature. Flip covers is also very latest and stylish. It can also be used as a gift to be showcased it to the loved ones.',
      highlights: 'Black, Shock Proof, Pack of: 1',
      category: 'Mobile',
      subCategory: 'Mobile Case',
      seller: 'SBMSMobileCovers',
      starRating: '3.5',
      rating: '10',
      reviews: '2',
      sellingPrice: '700',
      price: '1300',
      deliveryType: 'Free delivery',
      discount: '42',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.phoneCase2,
      title:
          'Sprig Liquid Silicone Back Cover for REDMI Note 12 5G, Redmi Note 12, Note 12',
      subTitle: '',
      description:
          'Enhance your REDMI Note 12 5G with the Sprig Liquid Silicone Back Cover. Crafted from premium shock-proof liquid silicone, this case offers ultimate protection and a stylish look. It fits perfectly, keeping your device scratch-proof and safeguarded from damage. Ideal for outdoor activities, it withstands bumps and accidental falls. The cover is 100% compatible with standard chargers and headphones, and its thickened design provides complete button access and enhanced protection. With raised screen edges, your front display stays safe. Plus, the microfiber lining prevents scratches. Choose from a range of vibrant colors. Our environmentally sustainable case supports wireless charging, is easy to clean, and retains its color. Elevate your smartphone with Sprig',
      highlights: 'White, Shock Proof, Silicon, Pack of: 1',
      category: 'Mobile',
      subCategory: 'Mobile Case',
      seller: 'Spring.store',
      starRating: '4',
      rating: '10',
      reviews: '8',
      sellingPrice: '800',
      price: '2500',
      deliveryType: 'Free delivery',
      discount: '69',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.latherCover,
      title:
          'KaseMast Back Cover for Apple Iphone 14, Iphone 14, Premium Leather Cove',
      subTitle: '',
      description:
          'Protect your iPhone 14 in style with KaseMast premium leather cover. Made from genuine leather, our cover not only looks great, but also provides excellent protection against scratches, bumps and drops. The soft microfiber lining on the inside ensures that your phone stays scratch-free and secure, while the slim design allows you to easily slip your phone in and out of your pocket or bag. Our cover is also wireless charging compatible, so you can charge your phone without having to remove the cover. Upgrade the look and feel of your iPhone 14 with our sleek and durable leather cover today!',
      highlights: 'Blue, Hard Case, Pack of: 1',
      category: 'Mobile',
      subCategory: 'Mobile Case',
      seller: 'SamyakEnterprises01',
      starRating: '4.5',
      rating: '9',
      reviews: '7',
      sellingPrice: '499',
      price: '1499',
      deliveryType: 'Free delivery',
      discount: '66',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.pocoMobile,
      title: 'POCO M4 Pro (Yellow, 128 GB)  (8 GB RAM)',
      subTitle: '',
      description:
          'With 8 GB of RAM, 128 GB of internal storage, a Helio G96 processor, UFS 2.2 WriteBooster, and Liquid Cooling Technology, the POCO M4 Pro is an elegantly built phone for all your multitasking requirements. This phone can steal the show everywhere you carry it due to its appealing design. This phone delivers a compelling visual experience with a 16.33 cm (6.43) savvy display, a refresh rate of 90 Hz, and a touch sampling rate of 180 Hz. This phone boasts a 5000 mAh battery that is capable of lasting for a long period. It also has a 33 W quick charging interface that can fully charge your phone in around 61 minutes. Additionally, This phone has a triple camera setup that includes a 64 MP back camera and an 8 MP Ultrawide lens with a 118-degree field of vision for taking high-quality photos. It is also equipped with a 16 MP front camera that helps capture stunning selfies.',
      highlights: '8 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
      category: 'Mobile',
      subCategory: 'Mobile Phone',
      seller: 'CLIENTEROecom',
      starRating: '4.1',
      rating: '21432',
      reviews: '1456',
      sellingPrice: '12999',
      price: '21999',
      deliveryType: 'Free delivery',
      discount: '40',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.samsungMobile,
      title: 'SAMSUNG Galaxy A34 5G (Awesome Violet, 128 GB)  (8 GB RAM)',
      subTitle: '',
      description:
          'The Samsung Galaxy A34 5G smartphone is the perfect choice if you want to capture mesmerising pictures. This smartphone features a large AMOLED display of about 16.76 cm (6.6) so that you can enjoy life-life visuals. It has a clean design with a glastic finish so that you can always stay classy. The OIS Camera featured in this smartphone enables you to click mesmerising pictures. It has a 5000 mAh battery that allows you to use this smartphone all day long without requiring frequent recharging.',
      highlights: 'Mobile phone, Cable, Ejection Pin, User Manual',
      category: 'Mobile',
      subCategory: 'Mobile Phone',
      seller: 'MYTHANGLORYRetail',
      starRating: '4.2',
      rating: '2227',
      reviews: '212',
      sellingPrice: '28999',
      price: '35499',
      deliveryType: 'Free delivery',
      discount: '18',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.appleMobile,
      title: 'APPLE iPhone 14 Plus (Blue, 128 GB)',
      subTitle: '',
      description: 'NA',
      highlights:
          'HDR Display, True Tone, Wide Colour (P3), Haptic Touch, Contrast Ratio: 20,00,000:1, Max Brightness: 800 nits, Peak Brightness: 1,200 nits, Fingerprint Resistant Oleophobic Coating, Support for Display of Multiple Languages and Characters Simultaneously',
      category: 'Mobile',
      subCategory: 'Mobile Phone',
      seller: 'BTPLD',
      starRating: '4.6',
      rating: '15655',
      reviews: '945',
      sellingPrice: '79900',
      price: '76999',
      deliveryType: 'Free delivery',
      discount: '3',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.motorolaMobile,
      title: 'MOTOROLA Edge 40 (Nebula Green, 256 GB)  (8 GB RAM)',
      subTitle: '',
      description:
          'Fuelled with a host of features, this Motorola Edge 40 smartphone brings to you a slim IP68 rated with 30 minutes of underwater dunk resistance. The 3D curved display, bezel-less design, vegan leather option, and sandblasted metal frame add to the phone’s elegance. Powered with a MediaTek 8020 processor, this phone is definitely a game changer. Available with 14 5G bands and WiFi6 networks, experience uninterrupted network connectivity. This phone boasts a 144 Hz 3D curved display and its 1200 nits brightness offers vibrant visuals. Take photography to the next level with the 50 MP main camera with wide aperture of f/1.4 and OIS, 13 MP ultra-wide camera, and 32 MP selfie camera. The 68 W TurboPower charger allows for a quick and full charge in just about ten minutes, and the 4400 mAh battery runs all day with 30 hours of continuous usage. This phone also has the capability of 15W wireless charging for charging on the move. Get a more user-friendly experience with the latest Android 13, and secure your privacy on the phone with the ThinkShield and Moto Secure protective features.',
      highlights:
          'Handset, Charger, USB Cable, Guides, Sim Tool, Protective Cover',
      category: 'Mobile',
      subCategory: 'Mobile Phone',
      seller: 'MTAILMODEECOM',
      starRating: '4.2',
      rating: '24350',
      reviews: '3523',
      sellingPrice: '29999',
      price: '34999',
      deliveryType: 'Free delivery',
      discount: '14',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.ideaPadLaptop,
      title:
          'Lenovo Ideapad Gaming 3 AMD Ryzen 5 Hexa Core 5600H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX 1650) 15ACH6 Gaming Laptop  (15.6 Inch, Shadow Black, 2.25 kg kg)',
      subTitle: '',
      description: 'NVIDIA GeForce GTX 1650 15.6 Inch Full HD, IPS, 250 nits, '
          'Anti-glare, 45% NTSC, Refresh Rate: 60 Hz Light Laptop without Optical Disk Drive',
      highlights: 'NVIDIA GeForce GTX 1650',
      category: 'Laptop',
      subCategory: 'Laptop',
      seller: 'PETILANTE Online',
      starRating: '4.2',
      rating: '404',
      reviews: '39',
      sellingPrice: '52490',
      price: '72990',
      deliveryType: 'Free delivery',
      discount: '28',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.appleMac,
      title:
          'APPLE 2020 Macbook Air M1 - (8 GB/256 GB SSD/Mac OS Big Sur) MGN63HN/A  (13.3 inch, Space Grey, 1.29 kg)',
      subTitle: '',
      description:
          'This Apple Macbook is powered by the Apple M1 chip and is easily portable so that you can carry it with you anywhere you want. This thin and light notebook is equipped with an 8-core CPU to handle all your tasks more efficiently. The 8-core GPU of this notebook takes graphic-intensive games and apps to a whole new level. It also comes with a 16-core Neural Engine to do machine learning tasks more effectively. Its fan-less design offers silent operations and has a long-lasting battery life which can last up to 18 hours on a single charge.',
      highlights:
          'MacBook Air, 30 W USB-C Power Adapter, USB-C Charge Cable (2m), User Guide, Warranty Documents',
      category: 'Laptop',
      subCategory: 'Laptop',
      seller: 'TREASURE HAUL ONLINE',
      starRating: '4.7',
      rating: '11628',
      reviews: '1001',
      sellingPrice: '82588',
      price: '99900',
      deliveryType: 'Free delivery',
      discount: '17',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.nokiaTv,
      title:
          'Nokia 164 cm (65 inch) Ultra HD (4K) LED Smart Android TV with Sound by Onkyo  (65TAUHDN)',
      subTitle: '',
      description:
          'Bring home this TV from Nokia and deep-dive into a world of lifelike colours. Boasting a sleek and stunning design, this TV features Micro Dimming and a MaxBrite Display to ensure that you enjoy clear and crisp detail with vibrant colours.',
      highlights: 'Supported Apps: Netflix|Prime Video|Disney+Hotstar|Youtube',
      category: 'TV',
      subCategory: 'TV',
      seller: 'Flashstar Commerce',
      starRating: '4.3',
      rating: '16398',
      reviews: '2800',
      sellingPrice: '79999',
      price: '37999',
      deliveryType: 'Free delivery',
      discount: '52',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.lgTV,
      title:
          'LG UQ7500 139 cm (55 inch) Ultra HD (4K) LED Smart WebOS TV 2022 Edition with Filmmaker Mode, AI Sound & Active HDR  (55UQ7500PSF)',
      subTitle: '',
      description:
          'Get larger than life visuals and unmatched movie watching experience on the LG UHD TV. This TV comes with a UHD 4K resolution display so that you can get a true-to-life visual quality and vivid colours. and streaming services with the With pre-installed streaming services on this TV, you can conveniently browse through your preferred content throughout the day. Whether you’re playing an action-packed game, or an adventure game, the Game Optimiser, Gaming Dashboard, and HGiG technology can make your gaming experience fast and seamless.',
      highlights: 'Supported Apps: Netflix|Prime Video|Disney+Hotstar|Youtube',
      category: 'TV',
      subCategory: 'TV',
      seller: 'About the Seller',
      starRating: '4.4',
      rating: '17220',
      reviews: '71990',
      sellingPrice: '41990',
      price: '71990',
      deliveryType: 'Free delivery',
      discount: '41',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.induction,
      title:
          'Pigeon Favourite IC 1800 W Induction Cooktop  (Black, Push Button)',
      subTitle: '',
      description:
          'You can add convenience to your daily kitchen tasks with the Pigeon Induction Cooktop. It has a portable design that enables you to move it across any place as per your requirements. In addition, as this induction cooktop consumes up to 1800 W, it ensures rapid and optimal temperature heating. The crystal plate on this slim and stylish induction cooktop adds to its long-lasting performance. Furthermore, you can opt for a healthy cooking option with this induction cooktop, which helps to keep all of the nutrients in food by cooking it at an ideal temperature.',
      highlights:
          'With an overall power consumption of up to 1800 W, the Pigeon Induction Cooktop provides rapid and even cooking. So, you can prepare your favourite dishes quickly on this kitchen appliance.',
      category: 'Kitchen',
      subCategory: 'Induction',
      seller: 'RetailNet',
      starRating: '4',
      rating: '475333',
      reviews: '61757',
      sellingPrice: '1649',
      price: '3195',
      deliveryType: 'Free delivery',
      discount: '48',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.grinder,
      title:
          'Lifelong LLCMB02 500 W Mixer Grinder (White, 3 Jars) & 1100 W Dry Iron (White, Blue) Super Combo',
      subTitle: '',
      description:
          'Make some delicious recipes at home with the help of this mixer grinder by Lifelong. With a multitude of features, such as the 3-speed setting knob, easy-grip handles, and a 500 W powerful motor, this mixer grinder makes cooking easy and convenient.',
      highlights: 'Suitable for: Wet Grinding, Chutney Grinding, Grating, '
          'Mincing, Dry Grinding, Blending, 500 W : Higher the Wattage, '
          'tougher the Juicing/Grinding',
      category: 'Kitchen',
      subCategory: 'Mixer Grinder',
      seller: 'KLPLWORLDRetail',
      starRating: '4.1',
      rating: '69935',
      reviews: '7146',
      sellingPrice: '1399',
      price: '3398',
      deliveryType: 'Free delivery',
      discount: '58',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.washingMachine1,
      title:
          'IFB 6 kg Steam Wash, Hard Water Wash, Active Color Protection 4 years Comprehensive Warranty Fully Automatic Front Load Washing Machine with In-built Heater White  (DIVA AQUA VSS 6008)',
      subTitle: '',
      description:
          'With features that ensure a great wash every time, this IFB Front Load Washing Machine lets you relax while enjoying a fantastic washing session. IFBs Front Load Washing Machine keeps track of all your laundry needs, from Aqua Energie, a filtration procedure for hard water, to up to 2x Power Dual Steam for a sanitary wash and power cleaning. Additionally, other features like Active Color Protection, Auto Tub Clean, Laundry Add, and Time Saver improve your entire washing experience while saving water, power, detergent, and time. Moreover, IFBs sturdy crescent moon drum made of stainless steel offers a soft water cushion that shields clothing from damage.',
      highlights:
          'Washing Machine, Outlet Pipe, Inlet Pipe, User Manual, Warranty Card',
      category: 'Washing Machine',
      subCategory: 'Washing Machine Front Loading',
      seller: 'OmniTechRetail',
      starRating: '4.2',
      rating: '8485',
      reviews: '687',
      sellingPrice: '23290',
      price: '26390',
      deliveryType: 'Free delivery',
      discount: '11',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.washingMachine2,
      title:
          'SAMSUNG 7 kg Diamond drum Fully Automatic Top Load Washing Machine Silver  (WA70A4002GS/TL)',
      subTitle: '',
      description:
          'Are you looking for a washing machine that does not damage your clothes? If yes, then bring home the Samsung washing machine that features the Centre Jet technology. This technology generates streams of water from the centre of the pulsator to prevent the clothes from settling on it and getting damaged. The diamond drum of this washing machine is gentle on clothes and even ensures that delicate clothes are not damaged. The child lock function prevents the tampering of the settings in between the wash function.',
      highlights:
          'Fully Automatic Top Load Washing Machines are ergonomically friendly and provide great wash quality',
      category: 'Washing Machine',
      subCategory: 'Washing Machine Top Loading',
      seller: 'OmniTechRetail',
      starRating: '4.3',
      rating: '8659',
      reviews: '658',
      sellingPrice: '15990',
      price: '19800',
      deliveryType: 'Free delivery',
      discount: '19',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.adidasShoes,
      title: 'Gambito M Running Shoes For Men  (Blue)',
      subTitle: '',
      description: 'Blue synthetic men sports running shoes',
      highlights: 'Running Shoes',
      category: 'Shoes',
      subCategory: 'Sports',
      seller: 'HSAtlastradeFashion',
      starRating: '4.1',
      rating: '70',
      reviews: '2',
      sellingPrice: '1513',
      price: '4299',
      deliveryType: 'Free delivery',
      discount: '64',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.jeans,
      title: 'Roadstar Men Skinny Mid Rise Blue Jeans',
      subTitle: '',
      description: 'Men Skinny Mid Rise Blue Jeans',
      highlights: 'blue Jeans',
      category: 'Cloths',
      subCategory: 'Men Jeans',
      seller: 'SAVADIKAFASHION',
      starRating: '3.6',
      rating: '1779',
      reviews: '131',
      sellingPrice: '626',
      price: '1899',
      deliveryType: 'Free delivery',
      discount: '67',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.smartWatch,
      title:
          'Fastrack Revoltt FS1|1.83 Display|BT Calling|Fastcharge|110+ Sports Mode|200+ WatchFaces Smartwatch  (Blue Strap, Free Size)',
      subTitle: '',
      description:
          '1.83" UltraVU Display with 500 nits Brightness, SingleSync BT Calling, 110+ Multisports, Sleep Monitor with REM Sleep, Stress Monitor, 24*7 HRM, SpO2, Womens Health, Music & Camera Control, In-Built Alarm, Stopwatch & Timer, In-Built Games, Multiple Menu Styles, IP68 Water Resistance, Upto 7 Days Battery',
      highlights:
          'Watch Head::Watch Strap::Charging Cable::Quick Start Guide::Product Manual',
      category: 'Watch',
      subCategory: 'Men Smart Watch',
      seller: 'RetailNet',
      starRating: '4.2',
      rating: '62461',
      reviews: '5840',
      sellingPrice: '1499',
      price: '3995',
      deliveryType: 'Free Delivery',
      discount: '62',
      offers: 'Bank Offers',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.toyCar,
      title:
          'SmallBoyToys WILLY RED 4X4 Powerful motors Off-Road battery operated ride on Jeep (1-8 yrs) Jeep Battery Operated Ride On  (Red)',
      subTitle: '',
      description:
          'Jeep models are always the first choice of children when choosing a fun car because the jeep is more compact but still no less powerful and flexible in moving. LB-888 electric jeep welcomes children to have fun and experience to have great moments, traveling on familiar roads in their playground. With an extremely attractive original design, the LB-888 jeep brings a cool beauty with a powerful engine for maximum power and ideal playtime with the vehicle. The car will carry your baby everywhere and learn all the good things from the world around him.',
      highlights: 'Remote, Assembling Manual in Box',
      category: 'Toy',
      subCategory: 'Remote Car',
      seller: 'Jays Company',
      starRating: '4',
      rating: '43',
      reviews: '5',
      sellingPrice: '13999',
      price: '23999',
      deliveryType: 'Free delivery',
      discount: '41',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.bedSheet,
      title:
          'haus & kinder 186 TC Cotton Double Floral Flat Bedsheet  (Pack of 1, Eleganza Pink)',
      subTitle: '',
      description: '1 Bedsheet, 2 Pillow cover',
      highlights: 'Material: Cotton',
      category: 'Home',
      subCategory: 'Decorator',
      seller: 'Jays Company',
      starRating: '4.3',
      rating: '4607',
      reviews: '377',
      sellingPrice: '1039',
      price: '1999',
      deliveryType: 'Free delivery',
      discount: '48',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.khattuCraft,
      title:
          'Khatu Crafts Om Swastik Key holder for home / office / kitchen / key holders / key holder for wall / key holder / Best decorative item for home décor / festive décor Mobile stand cum Wood Key Holder  (8 Hooks, Brown)',
      subTitle: '',
      description:
          'It is a real trouble when you lose your keys. You have to make little space in your house where you can put your keys. So be creative and make that space interesting and stylish. Khatu Crafts presents Awesome product to protect your keys. Buy this Wooden Laminated key holder cum mobile stand with charging space.',
      highlights: 'Hang Your cloths, Hang your mask, Hang your Key chains',
      category: 'Home',
      subCategory: 'Decorator',
      seller: 'KCRAFT',
      starRating: '4.5',
      rating: '3972',
      reviews: '2429',
      sellingPrice: '139',
      price: '999',
      deliveryType: 'Free delivery',
      discount: '86',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.wallWatch,
      title:
          'AJANTA Analog 20.5 cm X 20.5 cm Wall Clock  (Blue, With Glass, Standard)',
      subTitle: '',
      description: 'NA',
      highlights: 'Home Decor - Clocks & Wall Decor',
      category: 'Watch',
      subCategory: 'Home Decor - Clocks & Wall Decor',
      seller: 'JUSTINTIME',
      starRating: '3.8',
      rating: '64432',
      reviews: '8722',
      sellingPrice: '279',
      price: '299',
      deliveryType: 'Free delivery',
      discount: '6',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.cricketKit,
      title:
          'HF ECONOMY DSC Full Size ( Ideal For 15-21 Years ) Complete Cricket Kit',
      subTitle: '',
      description:
          '1 Cricket Bat , 1 Batting Legguard, 1 Batting Gloves, 1 Kitbag, 1 Thigh Guard, 1 Arm Guard, 1 Abdo Guard , 1Cricket Helmet, 1 pc red colour leather ball ',
      highlights: 'ECONOMY DSC Full Size ( Ideal For 15-21 Years ) Complete',
      category: 'Sports',
      subCategory: 'Cricket',
      seller: 'RC SONS RETAIL',
      starRating: '3.9',
      rating: '787',
      reviews: '105',
      sellingPrice: '3899',
      price: '18999',
      deliveryType: 'Free delivery',
      discount: '79',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.vinegar,
      title: 'Kapiva Apple Cider Vinegar  (500 ml)',
      subTitle: '',
      description:
          'Kapivas Apple Cider Vinegar is made from the finest, purest juice of himalayan apples. It is 100% natural, unpasteurized and unfiltered. The healthiest versions of vinegar contain The Mother. when observed carefully, some fine strands The Mother can be seen floating in the liquid. It is a beneficial bacteria with many health benefits. ??? Boosts heart health. ??? Acts as a natural deodorant and whitens teeth. ??? Cures bad breath and sore throat. ??? Promotes shiny hair and glowing skin. ??? Manages blood sugar.',
      highlights: '1 Apple Cider Vinegar Bottle',
      category: 'Food',
      subCategory: 'Vinegar',
      seller: 'Kapiva',
      starRating: '4.3',
      rating: '4456',
      reviews: '296',
      sellingPrice: '284',
      price: '299',
      deliveryType: 'Free delivery',
      discount: '5',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.caromBoard,
      title:
          'Little Champs Smooth Carrom Board(20 inch) for Kids With Coins Striker and Boric Powder 44 cm Carrom Board  (Brown)',
      subTitle: '',
      description: 'NA',
      highlights: 'Surface Material: Assam Plywood',
      category: 'Sports',
      subCategory: 'Indoor Game',
      seller: 'Solacecreations',
      starRating: '',
      rating: '',
      reviews: '',
      sellingPrice: '664',
      price: '1999',
      deliveryType: 'Free delivery',
      discount: '66',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.chocolate,
      title: 'Cadbury Dairy Milk Silk Bubbly Chocolate Bars  (6 x 50 g)',
      subTitle: '',
      description:
          'Cadbury Dairy Milk Silk is all about regaling in the richness and creaminess of chocolate. Indulge in a rich, smooth, and creamy celebration.Silk: The classic taste of Cadbury Dairy Milk chocolates only more creamy, more smooth, more indulging.Cadbury Dairy Milk Silk Bubbly is a fun bubbly twist to the classic Cadbury Dairy Milk Silk.This milk chocolate bar is a perfect sweet to indulge in all alone or as a chocolate gift pack for gifting on special occasions like birthdays and get-togethers.Every bar of Cadbury Dairy Milk Silk is made from 100% sustainable cocoa. It is suitable for vegetarians.',
      highlights: 'Milk Chocolate Plain flavor',
      category: 'Food',
      subCategory: 'Chocolate',
      seller: 'SuperComNet',
      starRating: '4.1',
      rating: '7041',
      reviews: '389',
      sellingPrice: '494',
      price: '510',
      deliveryType: 'Free delivery',
      discount: '3',
      offers: 'Bank Offer',
    ),
    ListingScreenProductMenuModal(
      id: '',
      image: Images.riceBranOil,
      title: 'Fortune Xpert Pro Immunity Rice Bran Oil Pouch  (4 x 1 L)',
      subTitle: '',
      description: 'Xpert Pro Immunity',
      highlights: '',
      category: 'Food',
      subCategory: 'Cooking Oil',
      seller: 'SuperComNet',
      starRating: '4.4',
      rating: '3436',
      reviews: '216',
      sellingPrice: '480',
      price: '480',
      deliveryType: 'Free delivery',
      discount: '1',
      offers: 'Bank Offer',
    ),
  ];
}
