// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1eEv3gqzFHU5-7OKybsIYMpJB8aXn8xY',
    appId: '1:929621933441:web:7131b0b82e6f34d9113c80',
    messagingSenderId: '929621933441',
    projectId: 'velocitybloom',
    authDomain: 'velocitybloom.firebaseapp.com',
    storageBucket: 'velocitybloom.appspot.com',
    measurementId: 'G-R0DV0Q7Z21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiN7j80u8OutJoPYFoNaTvC_HwGUtLFII',
    appId: '1:929621933441:android:123b70c62e6730c2113c80',
    messagingSenderId: '929621933441',
    projectId: 'velocitybloom',
    storageBucket: 'velocitybloom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAEmYfO3qhzO5B_mwaUqu8a3zB_rpoRI',
    appId: '1:929621933441:ios:e505cb99b4198278113c80',
    messagingSenderId: '929621933441',
    projectId: 'velocitybloom',
    storageBucket: 'velocitybloom.appspot.com',
    androidClientId: '929621933441-1d99cmks6nsu67fbub7sb8aqc13o8uts.apps.googleusercontent.com',
    iosClientId: '929621933441-4u9oco2t1rq7e47qku3d52mvaoipv22u.apps.googleusercontent.com',
    iosBundleId: 'com.example.velocitybloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOAEmYfO3qhzO5B_mwaUqu8a3zB_rpoRI',
    appId: '1:929621933441:ios:e505cb99b4198278113c80',
    messagingSenderId: '929621933441',
    projectId: 'velocitybloom',
    storageBucket: 'velocitybloom.appspot.com',
    androidClientId: '929621933441-1d99cmks6nsu67fbub7sb8aqc13o8uts.apps.googleusercontent.com',
    iosClientId: '929621933441-4u9oco2t1rq7e47qku3d52mvaoipv22u.apps.googleusercontent.com',
    iosBundleId: 'com.example.velocitybloom',
  );
}
